In [1]:
import numpy as np

SCALAR:
- 0 boyutludur(boyutsuz)
- Bir noktayı temsil eder.

In [3]:
scaler = np.array(21)
scaler

array(21)

In [18]:
scaler.ndim # boyutunu gösterir. boyut yok/boyutsuz

0

VEKTÖR:
- 1 boyutludur.
- Tek bir doğruyu temsil eder.
- Tek satır veya tek sütundur.

In [4]:
vektor = np.array([1,2,3]) 
vektor 

array([1, 2, 3])

In [19]:
vektor.ndim # değer tek bir satır(1 boyut) olarak döndü.

1

MATRİS:
- 2 boyutludur.
- Eni ve boyu vardır.(en ve boy örnek olarak kullanılmıştır.)
- Satırlar ve kolonlardan oluşur.

In [9]:
matris = np.array([
                  [1,2,3],
                  [1,2,3],
                  [1,2,3]  
                ])
matris 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [10]:
matris2 = np.array([[1,2,3], [1,2,3]])
matris2

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
matris2.ndim # değer iki satır ve iki kolon(2 boyut) olarak döndü.

2

TENSÖR:
- 3 boyutludur.

In [22]:
tensor = np.array([ # tensör ayracı
    [ # 1. matris ayracı
        [1,2,3], [1,2,3] # iki liste birer vektördür.
    ], 
    [ # 2. matris ayracı
        [1,2,3], [1,2,3]
    ]
]) 
tensor

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [13]:
tensor.ndim # değer 3 boyutlu olarak döndü.

3

In [58]:
tensor2 = np.array([[
                        [1, 2, 3], [1, 2, 3], [1, 2, 3]
                    ],
                    [
                        [1, 2, 3], [1, 2, 3], [1, 2, 3]
                    ],
                    [
                        [1, 2, 3], [1, 2, 3], [1, 2, 3]
                    ],
                    [
                        [1, 2, 3], [1, 2, 3], [1, 2, 3]
                    ]
])
tensor2

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [59]:
tensor2.ndim

3

##### NOT:
- Tensörler içerisinde matrisleri, matrisler vektörleri, vektörler ise skaler değerleri barındırır.

# size, shape, ndim, dtype
- size: Kaç elemandan oluştuğunun sayısını verir.
- shape: Kolon ve satır ya da boy ve en uzunluğunu verir.(Şeklini verir)
- ndim: Boyutunu verir.
- dtype: Elemanların tipini verir.

In [40]:
vektor = np.array([1,2,3,4,5,6])
matris = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
tensor = np.array([
    [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]],
    [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]],
    [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]],
    [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
])

In [16]:
vektor

array([1, 2, 3, 4, 5, 6])

In [46]:
vektor.ndim

1

In [17]:
vektor.size

6

In [18]:
vektor.shape

(6,)

In [49]:
vektor.dtype

dtype('int32')

In [19]:
matris

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [47]:
matris.ndim

2

In [20]:
matris.size

12

In [21]:
matris.shape 

(2, 6)

In [50]:
matris.dtype

dtype('int32')

In [41]:
tensor

array([[[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]]])

In [48]:
tensor.ndim

3

In [42]:
tensor.size

96

In [45]:
tensor.shape 
# ilk değer: matris sayısı, ikinci değer: bir matristeki vektör sayısı, üçüncü değer: bir vektör içindeki skaler(eleman) sayısı

(4, 3, 8)

In [51]:
tensor.dtype

dtype('int32')

# VERİ TİPİ DEĞİŞTİRME
- astype() 
- Dönüştürebileceği formatlarda kullanılır. Yani int32 tipi int64'e veya float64'e dönüştürülebilir fakat metine dönüştürülemez.

In [13]:
sayilar = np.array([1,2,3,4,5])
print(sayilar)
sayilar.dtype

[1 2 3 4 5]


dtype('int32')

In [11]:
sayilar2 = np.array([1,2.2,3,4,5])# array içinde 1 tane bile float değer bulunması bu dizinin türünün float olması için yeterli.
print(sayilar2)
sayilar2.dtype

[1.  2.2 3.  4.  5. ]


dtype('float64')

In [17]:
sayilar.astype("float64") # kalıcı olması için kendi değikenine atanmalı.(sayilar=sayilar.astype("int64"))

array([1., 2., 3., 4., 5.])

In [20]:
isim = np.array(["a", "b", "c"])
isim.dtype
isim.astype("int64") # Hata verir.

ValueError: invalid literal for int() with base 10: 'a'

// Dizi Oluşturulurken Tipleri Belirleme //

In [21]:
sayilar3 = np.array([1,2,3,4,5,6], dtype="int8")
print(sayilar3)
sayilar3.dtype

[1 2 3 4 5 6]


dtype('int8')

In [41]:
tarih = np.array(["2024-03-21"]) # yıl-ay-gün
print(tarih)
print(f"{tarih.dtype}: Önceki tip")

tarih = tarih.astype("datetime64") # dönüşüm
print(tarih)
print(f"{tarih.dtype}: Dönüştürülen tip")

['2024-03-21']
<U10: Önceki tip
['2024-03-21']
datetime64[D]: Dönüştürülen tip


# Slicing

In [5]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
a[3] # 3.index'i getirir.

23

In [7]:
a[4:7] # 4.indexten(dahil) 7.index(dahil deği)'e kadar

array([24, 25, 26])

In [8]:
a[:5] # 5.indexten öncesini getirir.

array([20, 21, 22, 23, 24])

In [10]:
a[3::2] # 3.index'ten başlayarak 2'şer arttırarak döndürme

array([23, 25, 27, 29])

In [14]:
[a[1], a[3], a[7]] # birden fazla slice işlemini aynı anda yapma

[21, 23, 27]

# Fancy Index 

In [15]:
c = np.arange(0,30,3)
c

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
secim = [3,4,5]
c[secim] # secim listesinde tanımlanan sayıları index olarak algıladı ve getirdi.

array([ 9, 12, 15])

Matrislerde Fancy Index

In [18]:
c2 = np.arange(9).reshape(3,3)
c2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
satir_secim = np.array([1,2])
sutun_secim = np.array([0,1])
c2[satir_secim, sutun_secim]

array([3, 7])

In [33]:
c2[0:, [1,2]] # slice ve fancy index birlikte kullanımı

array([[1, 2],
       [4, 5],
       [7, 8]])

# MATRİSLERDE SLICE İŞLEMİ

In [11]:
matris = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
matris.shape # ilk değer: kolon sayısı, ikinci değer: satır sayısı

(4, 4)

In [34]:
matris[0] # İlk satırı/ilk vektörü verir.

array([1, 2, 3, 4])

In [35]:
matris[1:3] # 1.vektörden(dahil) 3.vektöre(dahil değil) kadar olanı verir.

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
matris[2, 3] # ilk değer hangi vektör olacağını(satır),
             # ikinci değer o vektörün kaçıncı elemanı olacağını(kolon) belirler. Yani 2.vektörün 3.elemanı.

12

In [58]:
matris[:, 2] # tüm vektörlerin 2.elemanını(tüm satırların 2.kolonu) getir

array([ 3,  7, 11, 15])

In [59]:
matris[:, 1:3] # tüm vektörlerin 1'den 3.elemanına(tüm satırların 1'den 3.kolonuna kadar) kadar getir.

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [60]:
matris[1,:] # 1.vektörün tüm kolonlarını(1.satırın tüm kolonları) getir.

array([5, 6, 7, 8])

In [13]:
matris[1:3, 1:4] # 1.vektörden(satırdan)'den 3.vektöre kadar olan 1.kolondan 4.kolona kadar seçme

array([[ 6,  7,  8],
       [10, 11, 12]])

In [31]:
matris[[0,3], [1,2]]

array([ 2, 15])

# RASTGELE NUMPY DİZİLERİ OLUŞTURMA
- numpy içindeki random kullanılır. Son değer dahil değildir.

In [43]:
np.random.randint(1,45) # 1-45 arası rastegele scaler oluşturma

37

In [44]:
np.random.randint(1,30,(3)) # 1-30 arası 3 elemandan oluşan vektör oluşturma

array([15,  2, 12])

In [35]:
np.random.randint(1,20,(3,4)) # 1-20 arası 4 eleman(kolon) ve 3 vektörden(satırlık) oluşan bir matris elde etm

array([[ 2,  8, 16, 12],
       [15, 18,  4,  3],
       [10, 13,  3,  5]])

In [46]:
np.random.randint(1,100+1,(3,4,6)) # 1-101 arası 3 matris, her bir matris için 4 vektör ve her vektör için 6 elemandan oluşan tensor oluşturma

array([[[38, 31, 12,  4,  1, 76],
        [57, 92, 22, 48, 88, 58],
        [28, 64, 84, 84, 29, 99],
        [64, 17, 47, 39,  9, 81]],

       [[18, 91, 81, 35, 68, 62],
        [29,  8, 20, 33, 64, 58],
        [22, 88, 35, 83, 10, 32],
        [62, 72, 33, 92,  9, 89]],

       [[84, 17, 27, 84, 32, 70],
        [74, 24, 90, 19, 64, 61],
        [52, 23, 35, 27, 95, 11],
        [59, 30, 56, 69, 54, 40]]])

#  ARANG İLE NUMPY DİZİSİ OLUŞTURMA
- Arange, belli aralıklarda sayı üretmek için kullanılır.
- Başlangıç değeri dahil, bitiş değeri dahil değildir.

In [49]:
np.arange(200) # 0'dan 200'ye kadar sayı üretti.

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [50]:
np.arange(10,45) # 10'dan 45'e kadar olan değerler

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

In [55]:
np.arange(0,30,2) # 0'dan 30'a kadar olan sayıları 2'şer 2'şer getirme

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# LINSPACE KULLANIMI
- Aralık belirtilerek getirilen değeri belirtilen parça sayısı kadar böler.

In [86]:
np.linspace(1,100,8) # 1-100 arasını 8 eş parçaya bölme

array([  1.        ,  15.14285714,  29.28571429,  43.42857143,
        57.57142857,  71.71428571,  85.85714286, 100.        ])

# reshape METODU
- shape'i tekrar yapılandırmak için kullanılır.
- shape'i tekrar yapılandırılacak yapının size'ı aynı olmalı. Örneğin; shape=3,4 olan bir matrisin size'ı 12'dir. shape tekrar farklı olarak belirlenecekse size yine 12 olmalıdır.

In [6]:
m1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m1)
print(m1.shape)
m1.size

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


12

In [7]:
m1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [9]:
m1.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [10]:
m1.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [19]:
yeni_matris = np.random.randint(1,10,(5,6))
yeni_matris

array([[2, 4, 9, 9, 6, 9],
       [5, 3, 3, 4, 3, 2],
       [3, 8, 5, 9, 1, 6],
       [3, 4, 3, 6, 7, 2],
       [1, 2, 8, 9, 6, 3]])

In [20]:
yeni_matris.shape

(5, 6)

In [21]:
yeni_matris.size

30

In [22]:
yeni_matris.reshape(3,10)

array([[2, 4, 9, 9, 6, 9, 5, 3, 3, 4],
       [3, 2, 3, 8, 5, 9, 1, 6, 3, 4],
       [3, 6, 7, 2, 1, 2, 8, 9, 6, 3]])

# copy ve View METOTLARI
- view ile matris kopyalanır ve kopyalanan matristeki değişim ana matrisi etkiler.

In [29]:
ana_matris = np.random.randint(0,2,(4,5))
ana_matris

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1]])

In [30]:
view_matris = ana_matris.view()
view_matris

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1]])

In [32]:
view_matris[0] = [9,9,9,9,9]

In [35]:
print(view_matris) # view_matris'teki değişim ana_matris için de uygulandı.
ana_matris

[[9 9 9 9 9]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 0 1 1]]


array([[9, 9, 9, 9, 9],
       [1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1]])

In [37]:
ana_matris2 = np.random.randint(0,2,(5,6))
ana_matris2

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 0]])

In [38]:
copy_matris = ana_matris2.copy()
copy_matris

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 0]])

In [39]:
copy_matris[0] = [8,8,8,8,8,8]

In [40]:
print(copy_matris) # copy_matris'teki değişim ana_matris2 için geçerli olmadı.
ana_matris2

[[8 8 8 8 8 8]
 [0 1 0 1 1 1]
 [0 0 0 0 0 1]
 [0 1 1 1 1 1]
 [1 1 0 0 1 0]]


array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 0]])

# identity()
- Birim matris oluşturmak için kullanılır.
- Birim matriste satır ve kolon sayılarının eşit olması gerektiğinden tek bir değer alır ve bu değer hem satır sayısı hem de kolon sayısı olarak tanımlanır.

In [12]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# eye()
- Farklı türden birim matris oluşturmak için kullanır.
- Farklı türden kasıt satır ve kolon sayılarının eşit olmaması ve köşegen hattının başlangıcını belirleme(k parametresi) üzerinedir.
- k parametresi pozitif değer aldığında kolon boyunca, negatif bir değer aldığında ise satır boyunca ilerler.

In [9]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
np.eye(5,7) # Satır ve kolon sayıları eşit değil.

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [4]:
np.eye(6,6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.eye(6,6,k=3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.eye(6,6, k= -2) # 2.vektörün(3.satır) köşegenine 1 verir.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

# diag()
- Köşegen matris oluşturmak için kullanılır.
- Verilen değerlere göre köşegen matris oluşturur.
- Köşegen matriste satır ve kolon sayısı eşit olduğundan dolayı verilen değer sayısına göre bir köşegen matris oluşturulur.(5 eleman verildiyse 5x5 bir matris oluşturulur.)  
- k parametresine girilen değer kadar eşit sayıda satır ve kolon eklenir.
- diag() aynı zamanda var olan bir matrisin köşegen hattındaki değerleri de verir.

In [14]:
np.diag([3,7,9,12,65])

array([[ 3,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 12,  0],
       [ 0,  0,  0,  0, 65]])

In [16]:
np.diag([6,8,2])

array([[6, 0, 0],
       [0, 8, 0],
       [0, 0, 2]])

In [17]:
np.diag([4,4,4,4,4]) # scaler matris

array([[4, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

In [38]:
np.diag([4,5,6,7,8])

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])

// k PARAMETRESİ İLE KULLANIMI //

In [40]:
np.diag([4,5,6,7,8],k=3) # 3 satır ve kolon ekledi.

array([[0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
np.diag([4,5,6,7,8],k=-3) # 3 satır ve kolon ekledi.

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 0, 0, 0],
       [0, 0, 0, 0, 8, 0, 0, 0]])

// VERİLEN MATRİSİN KÖŞEGEN HATTI DEĞERLERİ BULMA //

In [49]:
r = np.random.randint(1,100,(6,6))
print(r)
np.diag(r) # verilen matrisin köşegen hattını verir.

[[82 85 49 64  4 86]
 [36 37 10 87 97 13]
 [45 12 78 52  9  2]
 [32 61 55 83 46 70]
 [10 67 29 24 54 43]
 [ 7  7 85 26 36 69]]


array([82, 37, 78, 83, 54, 69])

// HERHANGİ BİR MATRİSTEN ALINMIŞ KÖŞEGEN DEĞERLERİ İLE KÖŞEGEN MATRİS OLUŞTURMA //

In [54]:
k_matris = np.random.randint(1,100,(5,5))
print(k_matris)
print(np.diag(k_matris)) # köşegen hattının elemanları
np.diag(np.diag(k_matris)) # verilen matrisin köşegen hattındaki değerlerini içeren köşegen matris oluşturur.

[[ 1 28 12 30  8]
 [54 14 14 98 92]
 [ 5 92 74 91 33]
 [63 19  8 29 56]
 [51 82 13 97 42]]
[ 1 14 74 29 42]


array([[ 1,  0,  0,  0,  0],
       [ 0, 14,  0,  0,  0],
       [ 0,  0, 74,  0,  0],
       [ 0,  0,  0, 29,  0],
       [ 0,  0,  0,  0, 42]])

# MATRİS İŞLEMLERİ

In [1]:
import numpy as np

In [36]:
m1 = np.array([[4,7,3],[8,4,2],[6,2,1]])
m2 = np.array([[11,14,18],[16,13,12],[15,19,10]])

In [25]:
m1 + m2 # Toplama: Satır ve kolonları birbirine denk gelen elemanlar toplanır.

array([[15, 21, 21],
       [24, 17, 14],
       [21, 21, 11]])

In [28]:
m1 - m2 # Çıkarma: Satır ve kolonları birbirine denk gelen elemanlar çıkarılır.

array([[ -7,  -7, -15],
       [ -8,  -9, -10],
       [ -9, -17,  -9]])

In [29]:
m1 * m2 # Çarpma

array([[ 44,  98,  54],
       [128,  52,  24],
       [ 90,  38,  10]])

In [30]:
m3 = np.random.randint(1,100,(3,4))
m4 = np.random.randint(1,100,(4,5))

In [34]:
m3 / m4 # HATA: Boyutları aynı olmayan matrislerle işlem yapılamaz

ValueError: operands could not be broadcast together with shapes (3,4) (4,5) 

# ARRAY BİRLEŞTİRME(concatenation)

In [9]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [10]:
np.concatenate([x,y]) # vektör birleştirme

array([1, 2, 3, 4, 5, 6])

In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

In [12]:
np.concatenate([a,b]) # matris birleştirme

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.concatenate([a,b], axis=1) # matris birleştirme(sütün bazında)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# ARRAY AYIRMA(splitting)

In [14]:
x = np.array([1,2,3,99,99,3,2,1])

In [15]:
np.split(x, [3,5]) # parametreler: Hangi değer üzerinde işlem yapılacağı(x), kaçıncı elemana kadar(Önce 3'e kadar sonra 5'e kadar)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [17]:
d,e,f = np.split(x, [3,5]) # Bu kod çıktısını sırasıyla değişkenlere atama
print(d)
print(e)
print(f)

[1 2 3]
[99 99]
[3 2 1]


In [18]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.vsplit(m,[2]) # 2.satırdan bölme

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [22]:
np.hsplit(m, [2]) # 2.kolondan bölme

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# KOŞUL İŞLEMLERİ

In [34]:
k = np.array([1,2,3,4,5])
k

array([1, 2, 3, 4, 5])

In [35]:
k > 5

array([False, False, False, False, False])

In [41]:
k[k>2]

array([3, 4, 5])

###### EK BİLGİLER

In [1]:
import numpy as np

Boyut Değiştirme

In [4]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.reshape((1,9)) # vektörü matrise çevirme

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# MATAMATİKSEL İŞLEMLER

In [5]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [6]:
v * 4 # Her elaman 4 ile çarpıldı.

array([ 4,  8, 12, 16, 20])

In [7]:
v/7

array([0.14285714, 0.28571429, 0.42857143, 0.57142857, 0.71428571])

#### ufunc

In [8]:
np.subtract(v, 2) # Her elamandan 2 çıkartıldı.

array([-1,  0,  1,  2,  3])

In [9]:
np.add(v, 21) # Her elemana 21 eklendi.

array([22, 23, 24, 25, 26])

In [10]:
np.multiply(v, 5) # Her eleman 5 ile çarpıldı.

array([ 5, 10, 15, 20, 25])

In [14]:
np.divide(v, 5) # Her eleman 5 ile bölündü.

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.power(v,4) # Her elemanın 4.kuvveti alındı.

array([  1,  16,  81, 256, 625], dtype=int32)

In [18]:
np.mod(v, 2) # Her elemana mod işlemi uygulandı.

array([1, 0, 1, 0, 1], dtype=int32)

In [19]:
np.absolute(np.array([-4,-6,4,3,-3])) # Her elemanın mutlak değeri alındı.

array([4, 6, 4, 3, 3])

In [22]:
np.sin(240) # Sinüs alma

0.9454451549211168

In [23]:
np.cos(456) # Kosinüs alma

-0.8919912433578294

In [28]:
print(np.log(5)) # Logoritmasını alma
print(np.log2(5)) # Logoritmanın derecesi belirtilerek alma

1.6094379124341003
2.321928094887362
